StudentMangement/urls.py
from django.contrib import admin
from django.urls import path, re_path
from app01.views import depart, user, preetynum, admin, account, task, order, chart, file, city, ceshiredis
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    path('index/', ceshiredis.index),
    # 部门表
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/multi/', depart.dapart_multi),
    path('depart/delete/', depart.depart_delete),
    path('depart/<int:nid>/edit/', depart.depart_edit),

    # 用户表
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/model/form/add/', user.user_model_form_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),

    # 靓号表
    path('num/list/', preetynum.num_list),
    path('num/add/', preetynum.num_add),
    path('num/<int:nid>/edit/', preetynum.num_edit),
    path('num/<int:nid>/delete/', preetynum.num_delete),

    # 管理员表
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    # 任务管理
    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    path('task/add/', task.task_add),

    # 订单管理
    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/delete/', order.order_delete),
    path('order/detail/', order.order_detail),
    path('order/edit/', order.order_edit),

    # 数据统计
    path('chart/list/', chart.chart_list),
    path('chart/bar/', chart.chart_bar),

    # 文件上传
    path('file/upload/', file.file_upload),
    path('upload/form/', file.upload_form),
    path('upload/modelform/', file.upload_modelform),

    # 城市列表
    path('city/list/', city.city_list),
    path('city/add/', city.city_add),
]

app01/models.py
from django.db import models


class Admin(models.Model):
    username = models.CharField(verbose_name="账号", max_length=64, unique=True)
    password = models.CharField(verbose_name="密码", max_length=64)
    def __str__(self):
        return self.username

class Department(models.Model):
    '''部门表'''
    title = models.CharField(verbose_name='部门名称', max_length=64)
    def __str__(self):
        return self.title


class UserInfo(models.Model):
    '''员工表'''
    name = models.CharField(verbose_name='姓名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name='入职时间')
    depart = models.ForeignKey(verbose_name='所属部门', to='Department', to_field='id',
                               on_delete=models.CASCADE)  # 关联表删除，自己删除
    # depart = models.ForeignKey(to='Department', to_field='id', on_delete=models.SET_NULL, null=True, blank=True)  # 关联表删除，自己为空
    gender_choices = (
        (1, '男'),
        (2, '女')
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)
    def __str__(self):
        return self.name

class PreetyNum(models.Model):
    '''靓号表'''
    mobile = models.CharField(verbose_name='靓号号码', max_length=32)
    price = models.IntegerField(verbose_name='价格', default=0)
    level_choices = (
        (1, '1级'),
        (2, '2级'),
        (3, '3级'),
        (4, '4级'),
    )
    level = models.SmallIntegerField(verbose_name='等级', choices=level_choices, default=1)
    status_choices = (
        (1, '已占用'),
        (2, '未使用')
    )
    status = models.IntegerField(verbose_name='状态', choices=status_choices, default=2)


class TaskInfo(models.Model):
    level_choices = (
        (1, "紧急"),
        (2, "重要"),
        (3, "一般"),
        (4, "临时")
    )
    level = models.SmallIntegerField(verbose_name="任务等级", choices=level_choices, default=4)
    title = models.CharField(verbose_name="标题", max_length=64)
    detail = models.TextField(verbose_name="任务详情", max_length=1024)
    leader = models.ForeignKey(verbose_name="负责人", to='Admin', to_field="id", on_delete=models.CASCADE)

class Order(models.Model):
    oid = models.CharField(verbose_name="订单编号", max_length=128, unique=True)
    title = models.CharField(verbose_name="商品名称", max_length=64)
    price = models.IntegerField(verbose_name="商品价格")
    status_choices = (
        (1,"待支付"),
        (2,"已支付")
    )
    status = models.SmallIntegerField(verbose_name="商品状态", choices=status_choices, default=1)
    user = models.ForeignKey(verbose_name="用户", to=Admin, to_field="id", on_delete=models.CASCADE)

class Boss(models.Model):
    name = models.CharField(verbose_name="姓名", max_length=64)
    age = models.SmallIntegerField(verbose_name="年龄")
    img= models.CharField(verbose_name="头像", max_length=128)

class City(models.Model):
    # FileField, 在数据库中存储依然是路径
    name = models.CharField(verbose_name="名称", max_length=64)
    num = models.IntegerField(verbose_name="人口")
    img = models.FileField(verbose_name="Logo", max_length=64, upload_to='city')  # 文件需要指定一个media下的目录

app01/views/account.py
from django.shortcuts import render, HttpResponse, redirect
from app01 import models
from app01.utils.code import check_code
from io import BytesIO
from app01.utils.MyForm import LoginForm
from django_redis import get_redis_connection

def login(request):
    '''登录'''
    if request.method == 'GET':
        form = LoginForm()
        return render(request, "login.html", {'form': form})
    form2 = LoginForm(data=request.POST)
    if form2.is_valid():
        code_input = form2.cleaned_data.pop('code')
        # code_image = request.session.get('image')  # 这里使用session做的
        # 也可以用redis做
        coon = get_redis_connection()
        code_image = coon.get('image').decode('utf-8')

        if code_input.upper() != code_image.upper():
            form2.add_error("code", "验证码错误！")  # 手动添加错误信息
            return render(request, "login.html", {'form': form2})

        row_object = models.Admin.objects.filter(**form2.cleaned_data).first()  # 本身返回的是一个字典，字典可以作为筛选参数传入
        if not row_object:
            form2.add_error("password", "用户名或密码错误")  # form对象可以添加错误，在密码下面出现
            return render(request, "login.html", {'form': form2})
        # 将用户登录的信息生成Cookie,写入Session
        request.session['info'] = {'id': row_object.id, 'name': row_object.username}
        request.session.set_expiry(60 * 60 * 24 * 7)  # 重新将session的有效期拉长，避免操作了60s就过期了
        return redirect('/admin/list/')
    return render(request, "login.html", {'form': form2})


def image_code(request):
    '''生成图片验证码'''
    img, code_string = check_code()  # 调用函数生成验证码和图片
    # request.session['image'] = code_string  # 将验证码写入session，方便在登录的地方验证，有点像实例属性，大家都能用
    # request.session.set_expiry(60)  # 给session设置时长，这里是为了避免验证图片一直有效

    # 这里可以用redis
    coon = get_redis_connection('default')
    coon.set('image', code_string, ex=60)

    stream = BytesIO()
    img.save(stream, 'png')

    return HttpResponse(stream.getvalue())

def logout(request):
    '''注销用户'''
    request.session.clear()
    return redirect('/login/')

app01/views/admin.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.Pagination import Pagination
from app01.utils.MyForm import AdminModelModelForm, AdminResetModelModelForm, AdminEditModelModelForm

def admin_list(request):
    # 构造搜索条件
    filter_dict = {}
    search_data = request.GET.get('q', '')
    if search_data:
        filter_dict['username__contains'] = search_data

    # 根据搜索条件去数据库取数据
    queryset = models.Admin.objects.filter(**filter_dict)

    # 分页
    page_object = Pagination(request, queryset)

    context = {
        'queryset': page_object.page_queryset,
        'search_data': search_data,
        'page_str': page_object.html()
    }
    return render(request, "admin_list.html", context)

def admin_add(request):
    title = '新建管理员'
    if request.method == 'GET':
        form = AdminModelModelForm()
        return render(request, "change.html", {'form': form, 'title': title})
    form2 = AdminModelModelForm(request.POST)
    if form2.is_valid():
        form2.save()
        return redirect("/admin/list/")
    return render(request, "change.html", {'form': form2, 'title': title})

def admin_edit(request, nid):
    title = '修改管理员'
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:  # 判断存不存在，有可能多用户在线，你想编辑的时候，别人已经删了
        # return 错误页面
        return redirect("/admin/list/")
    if request.method == 'GET':
        form = AdminEditModelModelForm(instance=row_object)
        return render(request, "change.html", {'form':form,'title': title})
    form2 = AdminEditModelModelForm(data=request.POST, instance=row_object)
    if form2.is_valid():
        form2.save()
        return redirect("/admin/list/")
    return render(request, "change.html", {'form': form2, 'title': title})

def admin_delete(request, nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect("/admin/list/")

def admin_reset(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return redirect("/admin/list/")

    title = f'重置密码——{row_object.username}'

    if request.method == 'GET':
        form = AdminResetModelModelForm()
        return render(request, "change.html", {'form':form,'title': title})
    form2 = AdminResetModelModelForm(data=request.POST, instance=row_object)
    if form2.is_valid():
        form2.save()
        return redirect("/admin/list/")
    return render(request, "change.html", {'form': form2, 'title': title})

app01/views/ceshiredis.py
from django.shortcuts import HttpResponse
from django_redis import get_redis_connection

def index(request):
    coon = get_redis_connection('default')
    coon.set('name', 'willy', ex=10)

    value = coon.get('name')
    print(value)
    return HttpResponse('ok')

app01/views/chart.py
from django.shortcuts import render
from django.http import JsonResponse


def chart_list(request):
    '''数据统计'''
    return render(request, "chart_list.html")


def chart_bar(request):
    series_list = [
        {
            'name': '销量',
            'type': 'bar',
            'data': [5, 20, 36, 10, 10, 20]
        },
        {
            'name': '业绩',
            'type': 'bar',
            'data': [15, 10, 26, 30, 15, 50]
        },
    ]
    x_axis = ['1月', '2月', '3月', '4月', '5月', '6月']
    legend = ['销量', '业绩']
    result = {
        'status': True,
        'data': {
            'series_list': series_list,
            'x_axis': x_axis,
            'legend': legend
        }
    }
    return JsonResponse(result)

app01/views/city.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.BootstrpForm import BootstrapModelForm

def city_list(request):
    queryset = models.City.objects.all()
    return render(request, "city_list.html", {'queryset':queryset})

class CityModelForm(BootstrapModelForm):
    bootstrap_exclude_fields = ['img']
    class Meta:
        model = models.City
        fields = "__all__"

def city_add(request):
    title = "新建城市"
    if request.method == 'GET':
        form = CityModelForm()
        return render(request, "upload_form.html", {'form': form, 'title': title})
    form2 = CityModelForm(data=request.POST, files=request.FILES)
    if form2.is_valid():
        form2.save()  # modelform可以直接帮你搞定文件写入media/city/文件夹，文件路径写入数据库
        return redirect("/city/list/")
    return render(request, "upload_form.html", {'form': form2, 'title': title})

app01/views/depart.py
import math
from django.shortcuts import render, redirect, HttpResponse
from app01 import models
from app01.utils.Pagination import Pagination
import pandas as pd
# 部门操作
def depart_list(request):
    '''部门列表'''
    # 去数据库获取部门列表
    filter_dict = {}
    search_data = request.GET.get('q', '')
    if search_data:
        filter_dict['title__contains'] = search_data
    queryset = models.Department.objects.filter(**filter_dict)
    page_object = Pagination(request, queryset, page_size=10)
    context = {
                'search_data': search_data,
                'queryset': page_object.page_queryset,
                'page_str': page_object.html()
               }
    return render(request, 'depart_list.html', context)
def depart_add(request):
    '''添加部门'''
    if request.method == "GET":
        return render(request, 'depart_add.html')
    # 获取用户通过post提交的数据
    title = request.POST.get('title')
    #  保存到数据库
    models.Department.objects.create(title=title)
    return redirect('/depart/list/')
def depart_delete(request):
    '''删除部门'''
    nid = request.GET.get('nid')

    models.Department.objects.filter(id=nid).delete()

    return redirect('/depart/list/')
def depart_edit(request, nid):
    '''编辑部门'''
    if request.method == "GET":
        data = models.Department.objects.filter(id=nid).first()
        return render(request, 'depart_edit.html', {'data': data})
    new_title = request.POST.get('title')
    models.Department.objects.filter(id=nid).update(title=new_title)
    return redirect('/depart/list/')

def dapart_multi(request):
    '''批量添加'''
    excel_object = request.FILES.get("exc")
    data_list = pd.read_excel(excel_object)['部门'].tolist()
    for i in data_list:
        exists = models.Department.objects.filter(title=i).exists()
        if not exists:
            models.Department.objects.create(title=i)
    return redirect('/depart/list/')

app01/views/file.py
import os
from django.shortcuts import render, HttpResponse
from django import forms
from app01.utils.BootstrpForm import BootstrpForm, BootstrapModelForm
from app01 import models
from django.conf import settings


def file_upload(request):
    if request.method == 'GET':
        return render(request, "file_upload.html")
    data = request.POST
    file_object = request.FILES.get('file')
    # print(data)
    # print(file)
    with open(file_object.name, mode='wb') as f:
        for chunk in file_object.chunks():
            f.write(chunk)
    return HttpResponse("File Uploaded")


class UpForm(BootstrpForm):
    bootstrap_exclude_fields = ['img']
    name = forms.CharField(label='姓名')
    age = forms.CharField(label='年龄')
    img = forms.FileField(label='头像')


def upload_form(request):
    title = "Form 上传"
    if request.method == 'GET':
        form = UpForm()
        return render(request, "upload_form.html", {'form': form, 'title': title})
    form2 = UpForm(data=request.POST, files=request.FILES)  # 有文件格式需要写files=request.Files
    if form2.is_valid():
        # 通过form的形式，需要自己单独处理得到的字段
        # 图像需要先保存在路径，再把路径传给数据库
        img_obj = form2.cleaned_data.get('img')
        media_path = os.path.join('media', img_obj.name)
        f = open(media_path, mode='wb')
        for chunk in img_obj.chunks():
            f.write(chunk)
        f.close()
        name = form2.cleaned_data.get('name')
        age = form2.cleaned_data.get('age')
        img = media_path
        models.Boss.objects.create(name=name, age=age, img=img, )

        return HttpResponse('上传成功')
    return render(request, "upload_form.html", {'form': form2, 'title': title})


class CityModelForm(BootstrapModelForm):
    bootstrap_exclude_fields = ['img']
    class Meta:
        model = models.City
        fields = "__all__"


def upload_modelform(request):
    title = "ModelForm上传"
    if request.method == 'GET':
        form = CityModelForm()
        return render(request, "upload_form.html", {'form': form, 'title': title})
    form2 = CityModelForm(data=request.POST, files=request.FILES)
    if form2.is_valid():
        form2.save()  # modelform可以直接帮你搞定文件写入media/city/文件夹，文件路径写入数据库
        return HttpResponse('上传成功！')
    return render(request, "upload_form.html", {'form': form2, 'title': title})

app01/views/task.py
import json
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from app01 import models
from app01.utils.Pagination import Pagination
from app01.utils.MyForm import TaskModelForm


def task_list(request):
    queryset = models.TaskInfo.objects.all().order_by('-id')
    page_object = Pagination(request, queryset, page_size=5)
    form = TaskModelForm()
    context = {
        'form': form,
        'queryset': page_object.page_queryset,  # 分完页的数据
        'page_str': page_object.html()  # 页码
    }
    return render(request, "task_list.html", context)


@csrf_exempt
def task_ajax(request):
    print(request.POST)  # 接收ajax上传的数据
    print(request.POST.get('name'))  # 接收ajax上传的数据
    print(request.POST.get('age'))  # 接收ajax上传的数据
    data_dict = {
        "status": True,
        "data": [1, 2, 3, 4, 5, 6]
    }
    json_data = json.dumps(data_dict)
    return HttpResponse(json_data)  # 返回给ajax中success后函数的内容


@csrf_exempt
def task_add(request):
    print(request.POST)
    form = TaskModelForm(request.POST)
    if form.is_valid():
        form.save()
        data_dict = {"status": True}
        return HttpResponse(json.dumps(data_dict))

    data_dict = {"status": False, "error": form.errors}
    return HttpResponse(json.dumps(data_dict, ensure_ascii=False))

app01/templates/num_list.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <div style="margin-bottom: 15px" class="clearfix">
            <a class="btn btn-primary" href="/num/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建靓号
            </a>
            <div style="float:right">
                <form class="navbar-form navbar-left" method="get" style="margin:0">
                    <input type="text" name="q" placeholder="Search for..." class="form-control" value="{{ search_data }}"
                           style="width: 300px">
                    <button type="submit" class="btn btn-default">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </form>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                靓号列表
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>靓号号码</th>
                    <th>价格/元</th>
                    <th>等级</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.mobile }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_level_display }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>
                            <a class="btn btn-success btn-xs" href="/num/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/num/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div aria-label="...">
            <ul class="pagination">
                {{ page_str | safe }}
            </ul>
        </div>

    </div>
{% endblock %}

app01/templates/order_list.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <input id="btnAdd" type="button" value="添加订单" class="btn btn-primary" style="margin-bottom: 15px">
        <div style="float:right">
                <form class="navbar-form navbar-left" method="get" style="margin:0">
                    <input type="text" name="q" placeholder="Search for..." class="form-control" value="{{ search_data }}"
                           style="width: 300px">
                    <button type="submit" class="btn btn-default">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </form>
            </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                订单列表
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>订单编号</th>
                    <th>商品名称</th>
                    <th>价格/元</th>
                    <th>状态</th>
                    <th>管理员</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr uid="{{ obj.id }}">
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.oid }}</td>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>{{ obj.user }}</td>
                        <td>
                            <input uid="{{ obj.id }}" type="button" class="btn btn-success btn-xs btnEdit" value="编辑">
                            <input uid="{{ obj.id }}" type="button" class="btn btn-danger btn-xs btnDelete"
                                   value="删除">
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <ul class="pagination">
            {{ page_str | safe }}
        </ul>
    </div>

    <!--添加订单对话框-->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建</h4>
                </div>
                <div class="modal-body">
                    <form id="formAdd">
                        <div class="clearfix">
                            {% for item in form %}
                                <div class="form-group col-xs-6" style="position: relative; margin-bottom:25px">
                                    <label>{{ item.label }}</label>
                                    {{ item }}
                                    <span class="error-msg" style="position: absolute;color: red"></span>
                                </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                </div>
            </div>
        </div>
    </div>
    <!--删除订单对话框-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
                <h4>确定删除？</h4>
                <p>一旦删除订单，与此相关的信息将全部删除，此操作不可撤回！</p>
                <p style="text-align: right">
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">删除</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                </p>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        var DELETE_ID
        var EDIT_ID
        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();
        })

        function bindBtnAddEvent() {

            $("#btnAdd").click(function () {
                EDIT_ID = undefined;
                $("#formAdd")[0].reset()
                $("#myModalLabel").text("新建")
                $('#myModal').modal('show');
            })
        }

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                //清空错误信息
                $(".error-msg").empty();
                //发送ajax请求到后台，增加数据
                if (EDIT_ID) {
                    //编辑功能
                    doEdit();
                } else {
                    //新建功能
                    doAdd();
                }

            })
        }

        function doAdd() {
            $.ajax({
                url: "/order/add/",
                type: "post",
                data: $("#formAdd").serialize(),
                success: function (res) {
                    if (res.status) {
                        {#alert("保存成功");#}

                        $("#formAdd")[0].reset();

                        location.reload()
                    } else {
                        $.each(res.error, function (name, error_list) {
                            $("#id_" + name).next().text(error_list[0]);
                        })
                    }
                }
            })
        }
        function doEdit() {
            $.ajax({
                url: "/order/edit/" + "?uid=" + EDIT_ID,
                type: "post",
                data: $("#formAdd").serialize(),
                success: function (res) {
                    if (res.status) {
                        $("#formAdd")[0].reset();
                        location.reload()
                    } else {
                        if (res.tip) {
                            alert(res.tip)
                        } else {
                            $.each(res.error, function (name, error_list) {
                                $("#id_" + name).next().text(error_list[0]);
                            })
                        }

                    }
                }
            })
        }

        function bindBtnDeleteEvent() {
            $(".btnDelete").click(function () {
                $('#deleteModal').modal('show');
                DELETE_ID = $(this).attr("uid");
            })
        }

        function bindBtnConfirmDeleteEvent() {
            $("#btnConfirmDelete").click(function () {
                $.ajax({
                    url: "/order/delete/",     // /order/delete?uid=DELETE_ID
                    type: "get",
                    data: {
                        uid: DELETE_ID,
                    },
                    dataType: "json",
                    success: function (res) {
                        if (res.status) {
                            //不刷新页面的做法,防止你在填的时候，修改删除，一旦刷新，之前的信息就全没了，如果在第二页还会调到第一页
                            $('#deleteModal').modal('hide');
                            $("tr[uid=" + DELETE_ID + "]").remove();
                            DELETE_ID = 0
                            //刷新页面的做法
                            {#location.reload()#}
                        } else {
                            alert(res.error)
                        }
                    }
                })
            })
        }

        function bindBtnEditEvent() {
            $(".btnEdit").click(function () {
                $("#formAdd")[0].reset()  // 清空对话框中的数据
                var uid = $(this).attr("uid");
                EDIT_ID = uid;
                $.ajax({
                    url: "/order/detail/",
                    type: "get",
                    data: {
                        uid: uid
                    },
                    success: function (res) {
                        if (res.status) {

                            $.each(res.data, function (name, value) {
                                $("#id_" + name).val(value)  //form生成的标签会有id_xxx，给模态框的空白行填写内容
                            });
                            $("#myModalLabel").text("编辑");
                            $('#myModal').modal('show');
                        } else {
                            alert(res.error)
                        }
                    }
                })
            })
        }
    </script>
{% endblock %}

app01/templates/user_list.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <div style="margin-bottom: 15px" class="clearfix">
            <a class="btn btn-primary" href="/user/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户
            </a>
            <a class="btn btn-primary" href="/user/model/form/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户(ModelForm版本）
            </a>
            <div style="float:right">
                <form class="navbar-form navbar-left" method="get" style="margin:0">
                    <input type="text" name="q" placeholder="Search for..." class="form-control" value="{{ search_data }}"
                           style="width: 300px">
                    <button type="submit" class="btn btn-default">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </form>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户列表
            </div>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>性别</th>
                    <th>账户余额</th>
                    <th>入职时间</th>
                    <th>所属部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.password }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.get_gender_display }}</td>
                        <td>{{ obj.account }}</td>
                        <td>{{ obj.create_time|date:"Y-m-d" }}</td>
                        <td>{{ obj.depart.title }}</td>
                        <td>
                            <a class="btn btn-success btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div aria-label="...">
            <ul class="pagination">
                {{ page_str | safe }}
            </ul>
        </div>
    </div>
{% endblock %}